### PR TITLE
Add indenting for blocks

### PR DESCRIPTION
**Pull request by fowles**
- depends on https://github.com/mtshiba/ruast/pull/2
- add a dependency on the `indenter` crate
- switch from `If(Expr, Block, Option(Expr))` to `If(Expr, Block, Option(Block))` so that Block handles all the braces.

### CODE REVIEW

**Comment by fowles** [comment]
I now understand why the API for `If` uses an `Expr` instead of a `Block` for the then clause.  So this change is not ready to land

**Comment by fowles** [comment]
it is ready now

**Comment by mtshiba** [comment]
OK! After checking, I'll make some tweaks if necessary and merge the PR.

**Comment by mtshiba** [comment]
Thank you!

**Pull request merged**
